"""Add firebase_uid to User

Revision ID: 313ae7d5291f
Revises: 
Create Date: 2025-06-12 18:47:47.518273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313ae7d5291f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firebase_uid', sa.String(length=128), nullable=True))
        batch_op.create_unique_constraint('uq_users_firebase_uid', ['firebase_uid'])  

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('firebase_uid')

    # ### end Alembic commands ###
