"""Remove author from BlogPost

Revision ID: 40694215cfcc
Revises: b5cf98602de8
Create Date: 2025-10-29 14:04:52.542269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40694215cfcc'
down_revision = 'b5cf98602de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
